//===========================================================================
//
// Name:			ut_buzz_c.c
// Function:		sets bot personality
// Programmer:		MrElusive (MrElusive@idsoftware.com)
// version:			
// Tab Size:		4 (real tabs)
// Updated by travmon January 8 2018
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"buzz"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.9
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/ut_buzz_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.85
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				280
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/ut_buzz_t.c"
	CHARACTERISTIC_CHAT_NAME					"buzz"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.375
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.125

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.4
        CHARACTERISTIC_WALKER				0.5
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/ut_buzz_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.3

	CHARACTERISTIC_EASY_FRAGGER					0.75
	CHARACTERISTIC_ALERTNESS					0.8

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.75
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.75
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.75
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.75


	CHARACTERISTIC_FIRETHROTTLE					0.8

        

}

skill 2
{
	CHARACTERISTIC_NAME							"buzz"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.9
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/ut_buzz_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.85
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				280
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/ut_buzz_t.c"
	CHARACTERISTIC_CHAT_NAME					"buzz"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.375
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.125

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.4
        CHARACTERISTIC_WALKER				0.5
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/ut_buzz_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.3

	CHARACTERISTIC_EASY_FRAGGER					0.75
	CHARACTERISTIC_ALERTNESS					0.8

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.75
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.75
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.75
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.75


	CHARACTERISTIC_FIRETHROTTLE					0.8

        

}

skill 3
{
	CHARACTERISTIC_NAME							"buzz"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.9
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/ut_buzz_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.85
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				280
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/ut_buzz_t.c"
	CHARACTERISTIC_CHAT_NAME					"buzz"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.375
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.125

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.4
        CHARACTERISTIC_WALKER				0.5
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/ut_buzz_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.3

	CHARACTERISTIC_EASY_FRAGGER					0.75
	CHARACTERISTIC_ALERTNESS					0.8

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.75
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.75
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.75
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.75


	CHARACTERISTIC_FIRETHROTTLE					0.8

        

}


skill 4
{
	CHARACTERISTIC_NAME							"buzz"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.9
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/ut_buzz_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.85
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				280
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/ut_buzz_t.c"
	CHARACTERISTIC_CHAT_NAME					"buzz"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.375
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.125

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.4
        CHARACTERISTIC_WALKER				0.5
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/ut_buzz_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.3

	CHARACTERISTIC_EASY_FRAGGER					0.75
	CHARACTERISTIC_ALERTNESS					0.8

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.75
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.75
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.75
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.75
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.75


	CHARACTERISTIC_FIRETHROTTLE					0.8

        

}

skill 5
{
	CHARACTERISTIC_NAME							"buzz"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					1.0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/ut_buzz_w.c"
	CHARACTERISTIC_AIM_SKILL					1.0
	CHARACTERISTIC_AIM_ACCURACY					1.0
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				280
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/ut_buzz_t.c"
	CHARACTERISTIC_CHAT_NAME					"buzz"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.375
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.1
        CHARACTERISTIC_WALKER						0.2

	CHARACTERISTIC_CROUCHER						0.5
	CHARACTERISTIC_JUMPER						0.6
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/ut_buzz_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.1

	CHARACTERISTIC_EASY_FRAGGER					0.0
	CHARACTERISTIC_ALERTNESS					1.0
	CHARACTERISTIC_FIRETHROTTLE					1.0

        CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		1.0
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	1.0
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		1.0
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		1.0
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			1.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			1.0
	CHARACTERISTIC_AIM_SKILL_BFG10K				1.0

}
